### ISSUE TITLE
Write Single Register 0x06  I think it works badly

### ISSUE THREAD

**Issue by g6pl** [yaacov/ArduinoModbusSlave#26]
Hello
If I use Write Single Register 0x06, I can not send DATA to another Register. Always DATA is saved at Register 0.
If I use Write Multiple Registers 0x10, is all ok!
Is there an error in the library?

**Comment by g6pl** [comment]
Thank you for your response..
unfortunately, it's not my league ..
I can not do it;)

**Comment by yaacov** [comment]
> it's not my league ..

a - you can try :-)
b - I think the lib is ok ( from looking at the code, didn't try ... ), you can check again on your side, maybe you can see the problem in your code ?

**Comment by yaacov** [comment]
where in your code do you use the `address` ?

**Comment by g6pl** [comment]
![1](https://user-images.githubusercontent.com/16067485/50574176-4b164a00-0de3-11e9-8549-dfff60ad7a63.jpg)
![2](https://user-images.githubusercontent.com/16067485/50574181-523d5800-0de3-11e9-96bc-208901b19ef2.jpg)
1.jpg is OK
2.jpg is not

**Comment by g6pl** [comment]
If i use 0x06 write single register only is temperature1 ok in my code.
If i use 0x10 multiple register write temperature1 , 2 ,3 are OK

**Comment by yaacov** [comment]
`array_writeMemory[i]=slave.readRegisterFromBuffer(i);`
should be:
`array_writeMemory[i + address]=slave.readRegisterFromBuffer(i);` ?

**Comment by g6pl** [comment]
By removing parts of the program that were not necessary for me, I did not know that the address was needed. You are great! Thank you again for your help. You did a great job!!!
