### ISSUE TITLE
Wrong pin on ./extras/ModbusSetch.pdf

### ISSUE THREAD

**Issue by ekhiw** [yaacov/ArduinoModbusSlave#28]
pin 8 max485 should go to vcc. color of the wire is correct, but its look like you swapped with pin 5.

**Comment by yaacov** [comment]
Nice :+1:  :100: 

Thanks :heart: , can you make a PR with a corrected scatch ? 

Current design was done using http://fritzing.org/home/ , if you make a new one, please also attach the source, it will make it easier to contribute / change things in the future.
