### ISSUE TITLE
ArduinoModbusSlave And ArduinoModbusSlaveTCP Can NOT run in a sketch

### ISSUE THREAD

**Issue by yanzixiang** [yaacov/ArduinoModbusSlave#30]
so i create this
https://github.com/yanzixiang/ArduinoModbusSlaveAsyncTCPAndRTU

**Comment by yaacov** [comment]
NIce :+1:  do you make want to make a pull request ?

**Comment by yanzixiang** [comment]
> NIce 👍 do you make want to make a pull request ?

I think you should consider to mix the two repo into one ,
because they share a lot of codes.
