### ISSUE TITLE
Broadcast messages are not captured

### ISSUE THREAD

**Issue by falahati** [yaacov/ArduinoModbusSlave#32]
Hey Yaacov, 

Let me first say thank you for writing this library. Saved a lot of my time here.

However, broadcast messages are not captured. These type of messages are very useful to change a holding register network-wide and are usually sent with slave id `0`.
Unfortunately, however, this library only captures messages with message slave id equal to the configured slave id and ignores messages with slave id `0`.

This can be fixed easily and I can submit a PR. However, I think you should decide IF and how we should inform the user of the library about these type of messages as the current implementation of the callback method is not capable of that.

**Comment by yaacov** [comment]
Hi :heart: 

> This can be fixed easily and I can submit a PR

Please do :+1:

> IF and how we should inform the user of the library about these type of messages.

In the PR you will also have to update the readme :-)

We will also bump version number, to indicate that we have a new feature that is backward compatible ( I will take care of that :-) )
