### ISSUE TITLE
[Problems] Communication

### ISSUE THREAD

**Issue by falahati** [yaacov/ArduinoModbusSlave#33]
Ok, now, this might be a little picky. After all, a lot of these problems might not be so obvious when working with the library. But I was just checking the source code and decided it is best to report them here. Even tho I hope I can find some time to fix these myself; it's always better to know which parts can use improvements if I failed to do so.

* `micros( ) > timeout + last_receive_time`  should be replaced with `micros( ) - last_receive_time ) > timeout` and type to `uint64_t` to prevent overflow
* Read loop now processes requests as soon as it reads some part without checking if the message is actually complete; and therefore might modify the `lengthIn` or reject it altogether; this should be changed so requests are processed completely at least after 1.5T silence. (half the timeout) 
**OR/AND**
* Requests should be processed as received and ignored as soon as there is a problem (id not matching as an example) as a byte by byte basis, as well as for determining beforehand the number of bytes required for the message to be valid
* Buffer size should be increased to 256 as per Modbus standard max message size
* Library responses too fast (I had some problem with this myself). It should wait for at least 3.5T after receiving a request before sending the response. (or at least 1.5T after making sure the request ended with another 1.5T silence)

**Comment by yaacov** [comment]
Thanks !
