### ISSUE TITLE
rename writeStringToBuffer() to writeArrayToBuffer()

### ISSUE THREAD

**Issue by ProAce** [yaacov/ArduinoModbusSlave#52]
In my opinion this function is confusingly named as a String is typically a set of characters. I would suggest to change it to writeArrayToBuffer() as this better covers the intended purpose. This would mean a minor functionality break, but would help with readability.

Also wouldn't it be more logical to support uint16_t array's as Modbus is 16 bit values based?

**Comment by yaacov** [comment]
Don't feel strongly about it :-) I'll look at the code, and if I like it it's ok by me :unicorn:

**Comment by ProAce** [comment]
As it had me really confused when I first encountered it I changed it in my latest pull request. https://github.com/yaacov/ArduinoModbusSlave/pull/53
