### ISSUE TITLE
writeResponse critical error

### ISSUE THREAD

**Issue by RenePL** [yaacov/ArduinoModbusSlave#55]
https://github.com/yaacov/ArduinoModbusSlave/blob/3a09303400451ff7eee6422ad55ff814c4003990/src/ModbusSlave.cpp#L836

This line crash everything!!! ;( ... I dont check any other lines changed with this merge but I think you shoudl verify it...

Please fix it ASAP becouse now your all great work is totally not working!!!

**Comment by yaacov** [comment]
Thanks :green_heart:
