### ISSUE TITLE
change Slave_ID in void setup()

### ISSUE THREAD

**Issue by amirSaffari1234** [yaacov/ArduinoModbusSlave#79]
is there any solution to change Slave_ID in void_setup?
i want to set Slave_ID  with dip switch

**Comment by ProAce** [comment]
You can do that via the 'setUnitAdress()' function

**Comment by amirSaffari1234** [comment]
> setUnitAdress()

Thank you very much

**Comment by protechiot** [comment]
hi, unfortunately i can't change the id. 
I wrote the following line which is called every time the arduino uno receives a modbus message with an integer. 
setUnitAddress (new_id) or Modbus setUnitAddress (new_id).
However always remains the same, can someone help me? Thanks
