### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by maxgerhardt** [yaacov/ArduinoModbusSlave#95]
The current release (https://github.com/yaacov/ArduinoModbusSlave/releases) is 2.0.0 from 2017. A lot of things have changed since then. People downloading this library via the Arduino IDE library manager or PlatformIO (https://registry.platformio.org/libraries/yaacov/ModbusSlave/versions) get the latest stable as that 2017 version, with which the examples shown in the Github of course not work.

Can you create a new stable release, e.g. 2.1.0, so that people can get the latest version as a regular release version?

**Comment by maxgerhardt** [comment]
The version in `library.properties` was not updated, so all library crawlers will not see this new version:

https://github.com/yaacov/ArduinoModbusSlave/blob/v2.1.0/library.properties#L2

**Comment by yaacov** [comment]
2nt try :-)
https://github.com/yaacov/ArduinoModbusSlave/releases/tag/v2.1.1

**Comment by maxgerhardt** [comment]
Works! https://registry.platformio.org/libraries/yaacov/ModbusSlave/versions

![image](https://user-images.githubusercontent.com/26485477/196740256-4f8c8f8a-3e26-4c5a-927f-a497d24929be.png)
